// Shared Cafe Data - Used by all pages
// This data is LOCAL - Firebase only stores user credentials

const sampleCafes = [
  {
    docId: 'cafe_001',
    name: 'Amethyst Cafe',
    location: 'Royapettah',
    rating: 4.5,
    tables: 20,
    address: 'Amethyst, Whites Rd, Royapettah',
    area: 'Royapettah',
    reviews: 7953,
    price: '₹₹₹₹',
    hours: '10:00 AM – 10:30 PM',
    phone: '+91 44 4599 1633',
    tags: ['Serene','Pet Friendly','Al Fresco'],
    description: 'The best cafe in Chennai — serene atmosphere with cats, filter coffee, and lush greenery.',
    emoji: '🌸',
    color: '#5C4033',
    menu: [{name: 'Filter Coffee', price: '₹80'}, {name: 'Club Sandwich', price: '₹240'}, {name: 'Red Velvet Cake', price: '₹200'}],
    amenities: ['Pet Friendly', 'Garden', 'Gift Shop']
  },
  {
    docId: 'cafe_002',
    name: 'The Brew Room',
    location: 'Mylapore',
    rating: 4.4,
    tables: 15,
    address: '146, Dr Radha Krishnan Salai, Mylapore',
    area: 'Mylapore',
    reviews: 3461,
    price: '₹₹₹',
    hours: '10:00 AM – 11:00 PM',
    phone: '+91 97109 47380',
    tags: ['Coffee','Garden Seating','European'],
    description: 'A hidden gem for coffee lovers with warm cozy ambience and freshly brewed signature cold brews.',
    emoji: '☕',
    color: '#6B3A2A',
    menu: [{name: 'Cold Brew', price: '₹180'}, {name: 'Cappuccino', price: '₹150'}, {name: 'Avocado Toast', price: '₹280'}],
    amenities: ['WiFi', 'Outdoor Seating', 'Parking']
  },
  {
    docId: 'cafe_003',
    name: 'Chamiers Café',
    location: 'Alwarpet',
    rating: 4.3,
    tables: 18,
    address: '106, Pasumpon Muthuramalinga Thevar Rd, RA Puram',
    area: 'Alwarpet',
    reviews: 3335,
    price: '₹₹₹',
    hours: '8:30 AM – 10:30 PM',
    phone: '+91 44 4203 0734',
    tags: ['Brunch','Romantic','Vintage'],
    description: 'A Victorian-style bungalow cafe with soft lighting and wicker chairs — perfect for long conversations.',
    emoji: '🌿',
    color: '#3A5A40',
    menu: [{name: 'English Breakfast', price: '₹450'}, {name: 'Pancakes', price: '₹280'}, {name: 'Masala Chai', price: '₹120'}],
    amenities: ['Garden', 'Air Conditioned', 'Live Music']
  },
  {
    docId: 'cafe_004',
    name: 'Café de Paris',
    location: 'Teynampet',
    rating: 4.1,
    tables: 22,
    address: '24, Cenotaph Rd, Teynampet',
    area: 'Teynampet',
    reviews: 2255,
    price: '₹₹₹',
    hours: '12:00 PM – 11:00 PM',
    phone: '+91 98848 15553',
    tags: ['Bakery','Garden','Date Spot'],
    description: 'A dreamy glasshouse decked in bushes — looks magical at night with an in-house bakery.',
    emoji: '🥐',
    color: '#8B6914',
    menu: [{name: 'Croissant', price: '₹120'}, {name: 'Quiche', price: '₹220'}, {name: 'Hot Chocolate', price: '₹180'}],
    amenities: ['WiFi', 'Bakery', 'Romantic Ambiance']
  },
  {
    docId: 'cafe_005',
    name: 'Writer\'s Café',
    location: 'Gopalapuram',
    rating: 4.4,
    tables: 25,
    address: '98, Peter\'s Rd, Gopalapuram',
    area: 'Gopalapuram',
    reviews: 7612,
    price: '₹₹',
    hours: '9:00 AM – 10:00 PM',
    phone: '+91 89258 44029',
    tags: ['Books','Budget-friendly','Charity'],
    description: 'A cozy bookish spot with profits going to rehab causes. Great pizzas, pastas, and hot chocolate.',
    emoji: '📚',
    color: '#2D4A7A',
    menu: [{name: 'Margherita Pizza', price: '₹280'}, {name: 'Hot Chocolate', price: '₹160'}, {name: 'Chicken Sandwich', price: '₹220'}],
    amenities: ['Books', 'Quiet', 'Charity']
  },
  {
    docId: 'cafe_006',
    name: 'Soylent Green',
    location: 'Nungambakkam',
    rating: 4.2,
    tables: 12,
    address: '12, Khader Nawaz Khan Rd, Nungambakkam',
    area: 'Nungambakkam',
    reviews: 1876,
    price: '₹₹₹₹',
    hours: '11:00 AM – 11:00 PM',
    phone: '+91 44 4503 4567',
    tags: ['Vegan','Organic','Healthy'],
    description: 'Plant-based cafe with innovative vegan dishes and fresh cold-pressed juices.',
    emoji: '🌱',
    color: '#4A7C59',
    menu: [{name: 'Buddha Bowl', price: '₹320'}, {name: 'Green Smoothie', price: '₹180'}, {name: 'Vegan Burger', price: '₹280'}],
    amenities: ['Vegan', 'Organic', 'WiFi']
  },
  {
    docId: 'cafe_007',
    name: 'The Fat Penguin',
    location: 'Adyar',
    rating: 4.3,
    tables: 16,
    address: '67, 2nd Main Rd, Gandhi Nagar, Adyar',
    area: 'Adyar',
    reviews: 4234,
    price: '₹₹',
    hours: '8:00 AM – 10:00 PM',
    phone: '+91 98844 56789',
    tags: ['Family-friendly','Breakfast','Coffee'],
    description: 'Popular neighborhood cafe known for all-day breakfast and filter coffee.',
    emoji: '🐧',
    color: '#1E3A5F',
    menu: [{name: 'Masala Dosa', price: '₹120'}, {name: 'Filter Coffee', price: '₹60'}, {name: 'French Toast', price: '₹180'}],
    amenities: ['Family-friendly', 'Breakfast', 'Parking']
  },
  {
    docId: 'cafe_008',
    name: 'Dublin',
    location: 'Egmore',
    rating: 4.0,
    tables: 30,
    address: '21, Commander-in-Chief Rd, Egmore',
    area: 'Egmore',
    reviews: 2890,
    price: '₹₹₹',
    hours: '11:00 AM – 12:00 AM',
    phone: '+91 44 2827 8901',
    tags: ['Irish','Pub','Live Music'],
    description: 'Irish-themed cafe-pub with live music, craft beer, and continental food.',
    emoji: '🍀',
    color: '#2D5A3D',
    menu: [{name: 'Fish and Chips', price: '₹450'}, {name: 'Irish Coffee', price: '₹280'}, {name: 'Shepherd\'s Pie', price: '₹380'}],
    amenities: ['Live Music', 'Bar', 'Dance Floor']
  },
  {
    docId: 'cafe_009',
    name: 'Mathura Café',
    location: 'Triplicane',
    rating: 4.1,
    tables: 20,
    address: '45, Triplicane High Rd, Triplicane',
    area: 'Triplicane',
    reviews: 3124,
    price: '₹',
    hours: '6:00 AM – 10:00 PM',
    phone: '+91 44 2844 1234',
    tags: ['South Indian','Budget','Traditional'],
    description: 'Authentic South Indian filter coffee and snacks at pocket-friendly prices.',
    emoji: '🍵',
    color: '#8B4513',
    menu: [{name: 'Filter Coffee', price: '₹30'}, {name: 'Idli Sambar', price: '₹60'}, {name: 'Vadai', price: '₹20'}],
    amenities: ['Budget', 'Traditional', 'Quick Service']
  },
  {
    docId: 'cafe_010',
    name: 'The Gatsby',
    location: 'Nungambakkam',
    rating: 4.5,
    tables: 14,
    address: '89, Haddows Rd, Nungambakkam',
    area: 'Nungambakkam',
    reviews: 2156,
    price: '₹₹₹₹',
    hours: '12:00 PM – 1:00 AM',
    phone: '+91 95000 12345',
    tags: ['Rooftop','Luxury','Cocktails'],
    description: 'Upscale rooftop lounge with city views, artisanal cocktails, and fusion cuisine.',
    emoji: '🥂',
    color: '#C9B037',
    menu: [{name: 'Truffle Pasta', price: '₹680'}, {name: 'Craft Cocktail', price: '₹450'}, {name: 'Sushi Platter', price: '₹850'}],
    amenities: ['Rooftop', 'Full Bar', 'Valet Parking']
  },
  {
    docId: 'cafe_011',
    name: 'Kozmic Blues',
    location: 'Besant Nagar',
    rating: 4.2,
    tables: 18,
    address: '23, 6th Ave, Besant Nagar',
    area: 'Besant Nagar',
    reviews: 1834,
    price: '₹₹',
    hours: '4:00 PM – 11:00 PM',
    phone: '+91 98402 98765',
    tags: ['Music','Art','Hipster'],
    description: 'Bohemian cafe with live blues, local art, and artisanal coffee.',
    emoji: '🎸',
    color: '#4B0082',
    menu: [{name: 'Cold Brew', price: '₹150'}, {name: 'Avocado Toast', price: '₹220'}, {name: 'Chocolate Tart', price: '₹180'}],
    amenities: ['Live Music', 'Art Gallery', 'Board Games']
  },
  {
    docId: 'cafe_012',
    name: 'Marina Moon',
    location: 'Marina Beach',
    rating: 4.3,
    tables: 24,
    address: '1, Santhome High Rd, near Marina Beach',
    area: 'Marina Beach',
    reviews: 4521,
    price: '₹₹₹',
    hours: '5:00 AM – 11:00 PM',
    phone: '+91 44 2847 5555',
    tags: ['Sea View','Sunrise','Romantic'],
    description: 'Beachfront cafe with stunning sunrise views, perfect for early morning coffee.',
    emoji: '🌅',
    color: '#FF6B35',
    menu: [{name: 'Sunrise Coffee', price: '₹120'}, {name: 'Seafood Platter', price: '₹550'}, {name: 'Tender Coconut', price: '₹80'}],
    amenities: ['Sea View', 'Outdoor Seating', 'Sunrise Specials']
  }
];

// Helper function to initialize cafes in localStorage
function initializeCafes() {
  if (!localStorage.getItem('cafes')) {
    localStorage.setItem('cafes', JSON.stringify(sampleCafes));
    console.log('✅ Cafes initialized in localStorage');
  }
}

// Initialize on load
initializeCafes();
